CREATE TABLE IF NOT EXISTS statistics (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    value DOUBLE NOT NULL,
    calculation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
