<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sporttracker</groupId>
        <artifactId>sport-tracker-system</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>shared-library</artifactId>
    <packaging>jar</packaging>
    <name>Shared Library</name>
    <description>Common classes and utilities for Sport Tracker System</description>

    <dependencies>
        <!-- Spring Boot Starter Web (For common DTOs, Exceptions, Http Status) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>